name: 'Lint PR Description'
description: 'Ensures the PR Description has been completed correctly'
author: 'craigbroadman'
inputs:
  repo-token:
    description: 'Token with permissions to do repo things'
  whitelisted-authors-pattern:
    required: false
    description: 'Will skip checks for authors matching this regular expression pattern'
runs:
  using: 'node12'
  main: 'dist/index.js'