name: Release - Set Semantic Version and Kick Off Azure DevOps Builds

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: read
  discussions: read

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          # version 7 is not supported yet
          extra_plugins: |
            conventional-changelog-conventionalcommits@6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}